robot_cfg:
    kinematics:
#        use_usd_kinematics: False
#        usd_path: "robot/robdekon_description/robdekon_demo_scanning.usd"
#        usd_robot_root: "/robot"
#        isaac_usd_path: ""
#        usd_flip_joints: {}
#        usd_flip_joint_limits: []

        urdf_path: "robot/robdekon_description/demo_robdekon_scanning.urdf"
        asset_root_path: "robot/robdekon_description"

        base_link: "world"
        ee_link: "zimmer_ee_ur"
        link_names: ["zimmer_ee_ur", "zimmer_ee_iiwa"]
        lock_joints: null
        extra_links: null


        collision_link_names: ["iiwa_link_0_right", "iiwa_link_1_right", "iiwa_link_2_right", "iiwa_link_3_right", "iiwa_link_4_right",
                               "iiwa_link_5_right", "iiwa_link_6_right", "zimmer_match_robo_part_iiwa", "zimmer_gripper_iiwa", "zimmer_left_jaw_iiwa",
                               "iiwa_link_7_right", "shoulder_link", "upper_arm_link", "forearm_link", "wrist_1_link", "wrist_2_link",
                               "wrist_3_link", "zimmer_gripper_ur", "zimmer_left_jaw_ur"] # List[str]
        collision_spheres:
            iiwa_link_0_right:
                  - "center": [ -0.004, 0.022, 0.075 ]
                    "radius": 0.1 # 0.17247
            iiwa_link_1_right:
                  - "center": [ -0.004, -0.056, 0.144 ]
                    "radius": 0.11516
                  - "center": [ -0.013, -0.035, 0.057 ]
                    "radius": 0.11361
                  - "center": [ 0.001, -0.059, 0.211 ]
                    "radius": 0.10897
            iiwa_link_2_right:
                  - "center": [ 0.0, 0.001, 0.064 ]
                    "radius": 0.12797
                  - "center": [ -0.014, 0.147, 0.028 ]
                    "radius": 0.1059
                  - "center": [ -0.002, 0.065, 0.056 ]
                    "radius": 0.11579
                  - "center": [ 0.018, 0.151, 0.026 ]
                    "radius": 0.10362
            iiwa_link_3_right:
                  - "center": [ -0.003, 0.007, 0.055 ]
                    "radius": 0.11728
                  - "center": [ 0.001, 0.063, 0.199 ]
                    "radius": 0.11151
                  - "center": [ 0.003, 0.054, 0.16 ]
                    "radius": 0.11151
            iiwa_link_4_right:
                  - "center": [ 0.0, 0.006, 0.055 ]
                    "radius": 0.11777
                  - "center": [ 0.002, 0.121, 0.034 ]
                    "radius": 0.10655
                  - "center": [ -0.004, 0.051, 0.053 ]
                    "radius": 0.11249
                  - "center": [ -0.014, 0.129, 0.025 ]
                    "radius": 0.10457
                  - "center": [ 0.017, 0.146, -0.016 ]
                    "radius": 0.08872
            iiwa_link_5_right:
                  - "center": [ -0.025, 0.001, 0.053 ]
                    "radius": 0.09849
                  - "center": [ 0.012, 0.029, 0.071 ]
                    "radius": 0.09645
                  - "center": [ 0.002, 0.003, 0.017 ]
                    "radius": 0.0869
            iiwa_link_6_right:
                  - "center": [ -0.001, -0.017, 0.005 ]
                    "radius": 0.11102
                  - "center": [ -0.009, 0.019, -0.008 ]
                    "radius": 0.10217
                  - "center": [ -0.001, 0.013, 0.007 ]
                    "radius": 0.1061
                  - "center": [ 0.01, 0.018, -0.009 ]
                    "radius": 0.10118
                  - "center": [ 0.008, -0.033, 0.015 ]
                    "radius": 0.1002
            zimmer_match_robo_part_iiwa:
                  - "center": [ 0.0, 0.0, 0.0 ]
                    "radius": 0.05
            zimmer_gripper_iiwa:
                  - "center": [ 0.05, 0.0, 0.06 ]
                    "radius": 0.06
                  - "center": [ 0.0, 0.0, 0.06 ]
                    "radius": 0.06
                  - "center": [ -0.05, 0.0, 0.06 ]
                    "radius": 0.06
            zimmer_left_jaw_iiwa:
                  - "center": [ 0.0, 0.0, 0.1 ]
                    "radius": 0.06
            iiwa_link_7_right:
                  - "center": [ 0.012, -0.016, 0.023 ]
                    "radius": 0.06612
            shoulder_link:
                  - "center": [ -0.004, 0.017, -0.014 ]
                    "radius": 0.10067
                  - "center": [ 0.002, -0.01, -0.02 ]
                    "radius": 0.09467
            upper_arm_link:
                  - "center": [ 0.001, -0.015, 0.41 ]
                    "radius": 0.10004
                  - "center": [ -0.0, 0.0, 0.201 ]
                    "radius": 0.09949
                  - "center": [ -0.0, -0.015, 0.016 ]
                    "radius": 0.10004
                  - "center": [ 0.0, -0.001, 0.306 ]
                    "radius": 0.09893
                  - "center": [ 0.0, -0.0, 0.122 ]
                    "radius": 0.09949
                  - "center": [ 0.0, 0.0, 0.272 ]
                    "radius": 0.09949
            forearm_link:
                  - "center": [ -0.001, 0.01, 0.02 ]
                    "radius": 0.072 # 0.09308
                  - "center": [ -0.0, 0.0, 0.215 ]
                    "radius": 0.06 # 0.08707
                  - "center": [ -0.0, -0.0, 0.128 ]
                    "radius": 0.06 # 0.08707
                  - "center": [ -0.0, -0.0, 0.293 ]
                    "radius": 0.06 # 0.08707
                  - "center": [ -0.001, 0.015, 0.381 ]
                    "radius": 0.06 # 0.08256
                  - "center": [ 0.004, 0.023, -0.02 ]
                    "radius": 0.06 # 0.08106
                  - "center": [0.0, -0.005, 0.381 ]
                    "radius": 0.06 # 0.08106
                  - "center": [ -0.0, -0.001, 0.177 ]
                    "radius": 0.06 # 0.08657
            wrist_1_link:
                  - "center": [ 0.001, 0.082, 0.01 ]
                    "radius": 0.07 # 0.08397
            wrist_2_link:
                  - "center": [ -0.001, 0.01, 0.083 ]
                    "radius": 0.07 # 0.0839
            wrist_3_link:
                  - "center": [ -0.023, 0.062, -0.005 ]
                    "radius": 0.06428
                  - "center": [ 0.024, 0.062, -0.003 ]
                    "radius": 0.06339
            zimmer_gripper_ur:
                  - "center": [ 0.04, 0.0, 0.06 ]
                    "radius": 0.055
                  - "center": [ 0.0, 0.0, 0.06 ]
                    "radius": 0.055
                  - "center": [ -0.04, 0.0, 0.06 ]
                    "radius": 0.055
            zimmer_left_jaw_ur:
                  - "center": [ 0.0, 0.0, 0.2 ]
                    "radius": 0.15
        collision_sphere_buffer: 0.005
        extra_collision_spheres: {}
        self_collision_ignore: {
            "iiwa_link_0_right": ["iiwa_link_1_right", "iiwa_link_2_right", "iiwa_link_3_right"],
            "iiwa_link_1_right": ["iiwa_link_2_right", "iiwa_link_3_right"],
            "iiwa_link_2_right": ["iiwa_link_3_right", "iiwa_link_4_right"],
            "iiwa_link_3_right": ["iiwa_link_4_right", "iiwa_link_5_right"],
            "iiwa_link_4_right": ["iiwa_link_5_right", "iiwa_link_6_right"],
            "iiwa_link_5_right": ["iiwa_link_6_right"],
            "iiwa_link_6_right": ["iiwa_link_7_right", "zimmer_match_robo_part_iiwa", "zimmer_gripper_iiwa", "zimmer_left_jaw_iiwa"],
            "zimmer_match_robo_part_iiwa": ["iiwa_link_7_right", "zimmer_gripper_iiwa", "zimmer_left_jaw_iiwa"],
            "zimmer_gripper_iiwa": ["iiwa_link_7_right", "zimmer_left_jaw_iiwa"],
            "zimmer_left_jaw_iiwa": ["iiwa_link_7_right"],
            "shoulder_link": ["upper_arm_link"],
            "upper_arm_link": ["forearm_link", "shoulder_link"],
            "forearm_link": ["wrist_1_link", "wrist_2_link", "wrist_3_link", "zimmer_gripper_ur"],
            "wrist_1_link": ["wrist_2_link","wrist_3_link", "zimmer_gripper_ur", "zimmer_left_jaw_ur"],
            "wrist_2_link": ["wrist_3_link", "zimmer_gripper_ur", "zimmer_left_jaw_ur"],
            "wrist_3_link": ["zimmer_gripper_ur", "zimmer_left_jaw_ur"],
            "zimmer_gripper_ur": ["zimmer_left_jaw_ur"],
        }# Dict[str, List[str]]
        self_collision_buffer: {
          'shoulder_link': 0.05,
        } # Dict[str, float]

        use_global_cumul: True
        mesh_link_names: null # List[str]

        cspace:
            joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint',
                'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint',
                'iiwa_joint_1_right', 'iiwa_joint_2_right', 'iiwa_joint_3_right',
                'iiwa_joint_4_right', 'iiwa_joint_5_right', 'iiwa_joint_6_right', 'iiwa_joint_7_right'] # List[str]
            retract_config: [-1.7582847, 1.0767393, -1.9908632, -1.234158, -2.5762355, 0.80586416, -0.5913276, -0.73795456,
              1.5066859, -1.2984768, 2.8886852, 1.1761675, 0.93407667]

#          [-1.57, 0, -1.57, -1.383, -1.57, 0.00,
#                              0.0, -0.78, 0.0, -1.4, 0.0, 0.6, 0.0]
#          [-0.9480543, -0.4454736, 0.77819544, 0.8167688, 1.7210726, -1.6924853, 0.81541026, -1.491877,
#                             2.1596897, 0.6194632, 1.129039, 1.2903719, -0.07321112]
           # List[float]
            null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
            cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
            max_jerk: [500.0, 500.0, 500.0, 500.0, 500.0, 500.0, 500.0, 500.0, 500.0, 500.0, 500.0, 500.0, 500.0]
            max_acceleration: [5.0, 5.0, 3.0, 2.0, 2.0, 2.0, 5.0, 5.0, 3.0, 2.0, 2.0, 2.0, 2.0]
          #[3.0, 3.0, 2.0, 1.0, 1.0, 1.0, 3.0, 3.0, 2.0, 1.0, 1.0, 1.0, 1.0]