wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726331964.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.18
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 1024
dataset_dir:
  desc: null
  value: ../data/robdekon_icra25
dataset_file:
  desc: null
  value: robdekon_execution_time_data_fewer_collision_250k.h5
dropout:
  desc: null
  value: 0.01532498486383016
epochs:
  desc: null
  value: 100
hidden_dim:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.0026448360117805043
lr_scheduler_gamma:
  desc: null
  value: 0.7638806781955148
lr_scheduler_step:
  desc: null
  value: 20
n_layers:
  desc: null
  value: 5
target_type:
  desc: null
  value: curobo
use_pe:
  desc: null
  value: true
wd:
  desc: null
  value: 0.0008056005664429894
