wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726327553.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.18
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 1024
dataset_dir:
  desc: null
  value: ../data/robdekon_icra25
dataset_file:
  desc: null
  value:
  - robdekon_execution_time_data_with_collision_120k.h5
  - random_two_arm_states_collision_450k_fused_2024-09-14-17-04.h5
dropout:
  desc: null
  value: 0.09687128680207124
epochs:
  desc: null
  value: 100
hidden_dim:
  desc: null
  value: 512
lr:
  desc: null
  value: 0.00412097121203484
lr_scheduler_gamma:
  desc: null
  value: 0.7563550375313433
lr_scheduler_step:
  desc: null
  value: 10
n_layers:
  desc: null
  value: 6
target_type:
  desc: null
  value: ruckig
use_pe:
  desc: null
  value: true
wd:
  desc: null
  value: 0.0004258742694695324
